name: JS Bump

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      pnpm-version:
        type: string
        default: '11'

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
