name: Bump

on:
  workflow_call:

jobs:
  check-changesets:
    name: Check for changesets (consumer hook)
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.check.outputs.has_changesets }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - id: check
        uses: ./.github/actions/check-changesets

  bump:
    name: Bump (consumer hook)
    needs: check-changesets
    if: needs.check-changesets.outputs.has_changesets == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Bump
        uses: ./.github/actions/bump
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
